[colors.primary]
background = '#0f1416'
foreground = '#dee3e6'

[colors.selection]
text = '#dee3e6'
background = '#004e5d'

[colors.cursor]
text = '#0f1416'
cursor = '#85d2e8'

[colors.normal]
black   = '#0f1416'
red     = '#e64c4d'
green   = '#75d66e'
yellow  = '#dbcd7b'
blue    = '#3f92ab'
magenta = '#72a0ae'
cyan    = '#85d2e8'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f65'
green   = '#8be086'
yellow  = '#e8dc97'
blue    = '#8de0f8'
magenta = '#37878b'
cyan    = '#557f95'
white   = '#ffffff'
