[colors.primary]
background = '#0f1511'
foreground = '#dee4de'

[colors.selection]
text = '#dee4de'
background = '#005234'

[colors.cursor]
text = '#0f1511'
cursor = '#90d5ae'

[colors.normal]
black   = '#0f1511'
red     = '#e54b5b'
green   = '#7fd66e'
yellow  = '#dbc47b'
blue    = '#3e9c67'
magenta = '#769f88'
cyan    = '#90d5ae'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f71'
green   = '#94e086'
yellow  = '#e8d497'
blue    = '#9ae4ba'
magenta = '#3c884f'
cyan    = '#488469'
white   = '#ffffff'
